general_architecture:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  regions: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 100
  epsilon: 100

production_fixed_weighting:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'fixed weighting'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50

production_weighted_least_connection:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'weighted least connection'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50

production_least_connection:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'least connection'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50

production_weighted_round_robin:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'weighted round robin'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50

production_round_robin:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'round robin'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50

production_randomized_static:
  host: 'http://localhost'
  main_endpoint: 'work'
  port: 5000
  policy: 'randomized static'
  hosts_configuration: { 'emea': 1, 'us': 2, 'asia': 2}
  req_num: 50